CREATE TABLE IF NOT EXISTS users (
 id SERIAL PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(160) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 role VARCHAR(30) NOT NULL DEFAULT 'admin',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courses (
 id SERIAL PRIMARY KEY,
 name VARCHAR(160) NOT NULL,
 workload VARCHAR(50),
 description TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS classes (
 id SERIAL PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 course_id INTEGER REFERENCES courses(id) ON DELETE SET NULL,
 module VARCHAR(80),
 shift VARCHAR(50),
 year VARCHAR(10),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS professors (
 id SERIAL PRIMARY KEY,
 name VARCHAR(160) NOT NULL,
 email VARCHAR(160),
 phone VARCHAR(40),
 bio TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subjects (
 id SERIAL PRIMARY KEY,
 name VARCHAR(160) NOT NULL,
 class_id INTEGER REFERENCES classes(id) ON DELETE SET NULL,
 professor_id INTEGER REFERENCES professors(id) ON DELETE SET NULL,
 workload VARCHAR(50),
 description TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS schedules (
 id SERIAL PRIMARY KEY,
 class_id INTEGER REFERENCES classes(id) ON DELETE SET NULL,
 subject_id INTEGER REFERENCES subjects(id) ON DELETE SET NULL,
 weekday VARCHAR(30) NOT NULL,
 start_time TIME,
 end_time TIME,
 room VARCHAR(80),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS activities (
 id SERIAL PRIMARY KEY,
 title VARCHAR(200) NOT NULL,
 subject_id INTEGER REFERENCES subjects(id) ON DELETE SET NULL,
 class_id INTEGER REFERENCES classes(id) ON DELETE SET NULL,
 description TEXT,
 due_date DATE,
 points NUMERIC(8,2),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS materials (
 id SERIAL PRIMARY KEY,
 title VARCHAR(200) NOT NULL,
 subject_id INTEGER REFERENCES subjects(id) ON DELETE SET NULL,
 class_id INTEGER REFERENCES classes(id) ON DELETE SET NULL,
 material_type VARCHAR(60),
 url VARCHAR(500),
 description TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
 id SERIAL PRIMARY KEY,
 title VARCHAR(200) NOT NULL,
 class_id INTEGER REFERENCES classes(id) ON DELETE SET NULL,
 stage VARCHAR(120),
 due_date DATE,
 points NUMERIC(8,2),
 description TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS internships (
 id SERIAL PRIMARY KEY,
 title VARCHAR(200) NOT NULL,
 class_id INTEGER REFERENCES classes(id) ON DELETE SET NULL,
 company VARCHAR(180),
 deadline DATE,
 contact VARCHAR(160),
 description TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
 id SERIAL PRIMARY KEY,
 title VARCHAR(200) NOT NULL,
 event_date TIMESTAMP,
 location VARCHAR(180),
 audience VARCHAR(120),
 description TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
 id SERIAL PRIMARY KEY,
 name VARCHAR(160) NOT NULL,
 registration VARCHAR(80) UNIQUE,
 phone VARCHAR(40) UNIQUE,
 class_id INTEGER REFERENCES classes(id) ON DELETE SET NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
 setting_key VARCHAR(120) PRIMARY KEY,
 setting_value TEXT,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
 id BIGSERIAL PRIMARY KEY,
 phone VARCHAR(40) NOT NULL,
 direction VARCHAR(3) NOT NULL CHECK (direction IN ('in','out')),
 message TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_activities_due_date ON activities(due_date);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_messages_phone_created ON messages(phone, created_at DESC);
